[package]
name = "phl-library"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
sha256 = "1.4.0"
walkdir = "2.3.3"
image = "0.24.7"
rawloader = "0.37.1"
rawler = { git = "https://github.com/luckydye/dnglab" }
roxmltree = "0.18"
