# https://taskfile.dev

version: "3"

dotenv: [".env"]

includes:
  server:
    dir: apps/server
    taskfile: apps/server/Taskfile.yml

  app:
    aliases: [app]
    dir: apps/app
    taskfile: apps/app/Taskfile.yml

  website:
    aliases: [web]
    dir: apps/website
    taskfile: apps/website/Taskfile.yml

tasks:
  run:
    desc: Run a task recursivly in all included Taskfiles.
    vars:
      TASK: '{{.TASK | default "help"}}'
      TASKS:
        sh: echo $(task --list --json | jq -r '.tasks[] | select(.name | contains(":{{.TASK}}")).name')
    cmds:
      - task --parallel {{.TASKS}}

  setup:ubuntu:
    desc: Install system dependencies
    dir: "."
    cmds:
      - sudo apt update
      - sudo apt install -y libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libsqlite3-dev
      - task: setup

  setup:
    desc: Install dependencies
    dir: "."
    sources:
      - .rtx.toml
      - bun.lockb
      - package.json
      - Cargo.toml
      - Cargo.lock
      - "**/package.json"
      - .env
      - .env.example
    generates:
      - node_modules/**
      - target/**
    cmds:
      - cp -n .env.example .env 2> /dev/null || true
      - rtx install 2> /dev/null || true
      - task: codegen
      - bun install
      - cargo install cargo-watch
      - cargo install wasm-pack
      - cargo install tauri-cli --version "^2.0.0-alpha"
      - cargo check

  codegen:
    dir: "./packages/proto"
    cmds:
      - cargo install protobuf-codegen
      - bun x cargo run --bin force-build

  reset:
    desc: Reset repository files
    prompt: Do you really want to reset the repository?
    cmd: git clean -xdf .

  dev:
    desc: Run desktop app with server
    deps: [setup]
    cmds:
      - task --parallel server:dev app:dev

  dev:ios:
    desc: Run ios app in simulator
    deps: [setup]
    cmd: task --parallel server:dev app:dev:ios

  build:
    desc: Build app
    deps: [setup]
    cmd: task --parallel server:build app:build

  build:docker:
    desc: Build docker image for library server
    cmd: docker buildx build --platform linux/amd64 -f apps/server/Dockerfile --tag luckydye/tokyo:latest .

  check:
    desc: Check files
    dir: ./
    cmds:
      - cargo check
      - bun x biome check ./ {{.CLI_ARGS}}
