# https://taskfile.dev

version: "3"

dotenv: [".env"]

includes:

  library:
    aliases: [lib]
    prefix: "Library"
    dir: apps/library
    taskfile: apps/library/Taskfile.yml

  desktop:
    aliases: [app]
    prefix: "Desktop"
    dir: apps/desktop
    taskfile: apps/desktop/Taskfile.yml

  viewport:
    aliases: [vwp]
    prefix: "Viewport"
    dir: packages/viewport
    taskfile: packages/viewport/Taskfile.yml

tasks:

  setup:
    desc: Install dependencies
    dir: '{{.TASKFILE_DIR}}'
    sources:
      - .rtx.toml
      - bun.lockb
      - package.json
      - Cargo.toml
      - Cargo.lock
      - '**/package.json'
    cmds:
      - rtx install 2> /dev/null || true
      - bun install
      - task: codegen

  codegen:
    desc: Generate code from protobuf files
    dir: '{{.TASKFILE_DIR}}/packages/phl-proto'
    cmds:
      - bash ./generate.sh

  reset:
    desc: Reset repository files
    prompt: Do you really want to reset the repository?
    cmds:
      - git clean -xdf .

  dev:
    desc: Run desktop app with library
    vars:
      deps:
        sh: task setup
    deps: [setup, library:dev, desktop:dev]

  build:
    desc: Build app
    vars:
      deps:
        sh: task setup
    deps: [library:build, desktop:build]

  check:
    desc: Check files
    dir: ./
    cmds:
      - cargo check
      - bun x biome check ./ {{.CLI_ARGS}}
