# https://taskfile.dev

version: "3"

dotenv: [".env"]

includes:

  library:
    aliases: [lib]
    dir: apps/library
    taskfile: apps/library/Taskfile.yml

  desktop:
    aliases: [app]
    dir: apps/desktop
    taskfile: apps/desktop/Taskfile.yml

tasks:

  setup:
    desc: Install dependencies
    dir: '{{.TASKFILE_DIR}}'
    sources:
      - .rtx.toml
      - pnpm-lock.yaml
      - '**/package.json'
    cmds:
      - rtx install 2> /dev/null || true
      - pnpm i

  reset:
    desc: Reset repository files
    prompt: Do you really want to reset the repository?
    cmds:
      - git clean -xdf .

  dev:
    desc: Run desktop app with library
    vars:
      deps:
        sh: task setup
    deps: [setup, library:dev, desktop:dev]

  build:
    desc: Build app
    vars:
      deps:
        sh: task setup
    deps: [library:build, desktop:build]

  check:
    desc: Check files
    dir: ./
    cmds:
      - cargo check
      - npx biome check ./ {{.CLI_ARGS}}
