# https://taskfile.dev

version: "3"

silent: true

dotenv: [".env"]

includes:

  library:
    aliases: [lib]
    dir: apps/library
    taskfile: apps/library/Taskfile.yml

  desktop:
    aliases: [app]
    dir: apps/desktop
    taskfile: apps/desktop/Taskfile.yml

tasks:

  dev:
    desc: Run desktop app with library
    deps: [library:dev, desktop:dev]

  build:
    desc: Build app
    deps: [library:build, desktop:build]

  check:
    desc: Check files
    dir: ./
    cmds:
      - cargo check
      - npx biome check ./ {{.CLI_ARGS}}
