[tasks.dev]
description = "Run library in dev"
run = ["cargo watch -x run"]

[tasks.build]
description = "Build library"
sources = ["src/**/*.rs"]
run = [
    "cargo build -Z unstable-options --out-dir dist",
    "chmod +x dist/library",
]

[tasks.install]
description = "Install Library"
run = ["cargo install --path ."]

[tasks.start]
description = "Start compiled library"
dependencies = ["build"]
run = ["./dist/library"]
