[package]
name = "tauri-plugin-tokyo"
version = "0.0.0"
authors = ["You"]
description = ""
edition = "2021"
rust-version = "1.65"
exclude = ["/node_modules"]
links = "tauri-plugin-tokyo"

[target]

[dependencies]
tauri = { version = "2.0.0-beta.12" }
serde = "1.0"
serde_json = "1.0.105"
thiserror = "1.0"
tokyo-proto = { path = "../proto", features = ["protoc"] }
tokyo-library = { path = "../library" }
tokyo-shadow = { path = "../shadow" }
anyhow = "1.0.75"
tokio = { version = "1.35.0", features = ["rt", "rt-multi-thread", "macros"] }

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.8" }
tauri-plugin = { version = "2.0.0-beta.10", features = ["build"] }
