[package]
name = "phl-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = { version = "3.2.0", features = ["with-bytes"] }
bytes = "1"

[build-dependencies]
protobuf-codegen = "3.2.0"
