[package]
name = "tauri-plugin-library"
version = "0.0.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.65"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-library"

[dependencies]
tauri = { version = "2.0.0-alpha.14" }
serde = "1.0"
thiserror = "1.0"

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.8" }
