[package]
name = "tokyo-library"
version = "0.1.0"
edition = "2021"

[dependencies]
tokyo-shadow = { path = "../shadow" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
sha256 = "1.4.0"
walkdir = "2.3.3"
image = "0.24.7"
rawloader = "0.37.1"
rawler = { git = "https://github.com/luckydye/dnglab" }
roxmltree = "0.18"
tokio = "1.32.0"
anyhow = "1.0.75"
sysinfo = { version = "0.29.10", features = ["serde"] }
futures = "0.3.29"

[dependencies.uuid]
version = "1.4.1"
features = ["v4"]
