[package]
name = "hello_world_simple"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
publish = false


[dependencies]
eframe = { version = "*", features = [
  "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }
env_logger = "0.10"
