[package]
name = "preview"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

[dependencies]
shadow = { path = "../../packages/shadow" }
eframe = { version = "*", features = [
  "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }
env_logger = "0.10"
