[package]
name = "phl-image"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.7"
serde = { version = "1.0", features = ["derive"] }
rawloader = "0.37.1"
rawler = { git = "https://github.com/luckydye/dnglab" }
sha256 = "1.4.0"
