[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
walkdir = "2.3.3"
phl-image = { path = "../../crates/phl-image" }
phl-library = { path = "../../crates/phl-library" }
urlencoding = "2.1.3"
sha256 = "1.4.0"
