[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
image = "0.24.7"
rawloader = "0.37.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
walkdir = "2.3.3"
