[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.1"
actix-web-actors = "4.2.0"
actix-web = "4.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
walkdir = "2.3.3"
phl-image = { path = "../../packages/phl-image" }
phl-library = { path = "../../packages/phl-library" }
phl-proto = { path = "../../packages/phl-proto" }
urlencoding = "2.1.3"
sha256 = "1.4.0"
