# https://taskfile.dev

version: "3"

silent: true

tasks:
  dev:
    desc: Run library in dev
    prefix: "library"
    cmds:
      - cargo run

  build:
    desc: Build library
    sources:
      - "src/**/*.rs"
    cmds:
      - cargo build -Z unstable-options --out-dir dist
      - chmod +x dist/library

  start:
    desc: Start compiled library
    deps: [build]
    cmds:
      - ./dist/library
