[package]
name = "shadow"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sha256 = "1.4.0"
image = "0.24.7"
rawloader = "0.37.1"
rawler = { git = "https://github.com/luckydye/dnglab" }
roxmltree = "0.18"
tokio = "1.32.0"
anyhow = "1.0.75"

[dependencies.uuid]
version = "1.4.1"
features = ["v4"]
