[package]
name = "tokyo-shadow"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rawler = { git = "https://github.com/luckydye/dnglab" }
tokio = "1.32.0"
pix = "0.13.3"                                          # Pixel / raster image library
# xmp_toolkit = "*"                                       # Rust-language bindings for Adobe's XMP Toolkit
# colorspace = "*"
image = "0.24.7"
imagepipe = "*"
