[package]
name = "tokyo-shadow"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rawler = { git = "https://github.com/luckydye/dnglab", rev = "4aafb2e" }
tokio = "1.32.0"
image = "0.24.7"
anyhow = "1.0.75"
srgb = "0.3.2"
kolor = "0.1.9"
