# https://taskfile.dev

version: "3"

silent: true

tasks:
  dev:
    desc: Run app
    dir: ./
    cmds:
      - cargo tauri dev

  dev:web:
    desc: Run app
    dir: ./
    cmds:
      - bun ./dev.ts

  build:
    desc: Build app
    dir: ./
    cmds:
      - cargo tauri build
