# https://taskfile.dev

version: "3"

silent: true

tasks:
  tauri:dev:
    dir: ./
    cmds:
      - cargo tauri dev

  ui:dev:
    dir: ./
    cmds:
      - bun x app dev

  tauri:build:
    dir: ./
    cmds:
      - cargo tauri build

  ui:build:
    dir: ./
    cmds:
      - bun x app build

  dev:
    desc: Dev
    prefix: "desktop"
    dir: ./
    deps: [ui:dev, tauri:dev]

  build:
    desc: Build app
    dir: ./
    cmds:
      - task: ui:build
      - task: tauri:build
