[package]
name = "tokyo-db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
libsql-client = "0.33.2"
serde_json = "1.0.105"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35.0", features = ["rt", "rt-multi-thread", "macros"] }
url = "2.5.0"
sha256 = "1.4.0"
sysinfo = { version = "0.29.10", features = ["serde"] }

[dependencies.uuid]
version = "1.4.1"
features = ["v4"]
