[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
libsql-client = "0.33.2"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.35.0", features = ["rt", "rt-multi-thread", "macros"] }
url = "2.5.0"
