# https://taskfile.dev

version: "3"

silent: true

tasks:
  tauri:dev:
    dir: ./
    cmds:
      - cargo tauri dev

  tauri:dev:ios:
    dir: ./
    cmds:
      - cargo tauri ios dev

  ui:dev:
    dir: ./
    cmds:
      - bun x tokyo-ui dev

  tauri:build:
    dir: ./
    cmds:
      - cargo tauri build

  ui:build:
    dir: ./
    cmds:
      - bun x tokyo-ui build

  dev:ios:
    desc: Dev ios
    prefix: ios
    dir: "./"
    deps: [ui:dev, tauri:dev:ios]

  dev:
    desc: Dev
    prefix: "desktop"
    dir: ./
    deps: [ui:dev, tauri:dev]

  build:
    desc: Build app
    dir: ./
    cmds:
      - task: ui:build
      - task: tauri:build
