# https://taskfile.dev

version: "3"

silent: true

tasks:
  tauri:dev:
    dir: ./
    cmds:
      - cargo tauri dev

  tauri:dev:ios:
    dir: ./
    cmds:
      - cargo tauri ios dev

  tauri:build:ios:
    dir: ./
    cmds:
      - cargo tauri ios build

  tauri:build:
    dir: ./
    cmds:
      - cargo tauri build

  ui:dev:
    dir: ./
    cmds:
      - bun x tokyo-ui dev

  ui:build:
    dir: ./
    cmds:
      - bun x tokyo-ui build

  dev:
    desc: Dev
    prefix: "desktop"
    dir: ./
    cmd: task --parallel ui:dev tauri:dev

  dev:ios:
    desc: Dev ios
    prefix: ios
    dir: "./"
    cmd: task --parallel ui:dev tauri:dev:ios

  build:
    desc: Build app
    dir: ./
    cmds:
      - task: ui:build
      - task: tauri:build

  start:
    desc: Start app in production
    dir: ../../target/release
    cmds:
      - ./app
