name: Docker Image CI

on:
  push:
    branches: ["main", "feat/client-api"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
        with:
          version: 3.x
      - name: Build the Docker image
        run: task build:docker
      - name: Tag image
        run: docker tag tokyo/library:latest registry.luckydye.de/tokyo/library:latest
      - name: Push registry
        run: docker push registry.luckydye.de/tokyo/library:latest
