version: 3

silent: true

tasks:
  dev:
    desc: Viewport dev command
    prefix: "viewport"
    cmds:
      - task build --watch

  build:
    desc: Build wasm
    dir: "."
    sources:
      - src/*.rs
    generates:
      - pkg/*
    cmds:
      - wasm-pack build --target web
